const state={graph:null,report:null,selected:null,direction:"both",limit:18,edge:null};
const $=id=>document.getElementById(id);
const canonical="GITHUB_CREATE_AN_ISSUE_COMMENT";
const short=s=>s.replace(/^GITHUB_/,"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
Promise.all([fetch("/dependency_graph.json").then(r=>r.json()),fetch("/inference_report.json").then(r=>r.json())]).then(([graph,report])=>{state.graph=graph;state.report=report;state.selected=graph.nodes.some(n=>n.id===canonical)?canonical:graph.nodes[0]?.id;const example=graph.edges.find(e=>e.from==="GITHUB_LIST_REPOSITORY_ISSUES"&&e.to===canonical&&e.label==="issue_number");if(example)state.edge=`${example.from}\0${example.to}\0${example.label}`;$("node-count").textContent=graph.nodes.length.toLocaleString();$("edge-count").textContent=graph.edges.length.toLocaleString();$("mode").textContent=report.run.mode;bind();render();if(example)inspect(example);}).catch(e=>{$("selected-title").textContent="Could not load graph";$("inspector-content").innerHTML=`<p class="muted">${esc(e.message)}. Run <code>npm run visualize</code> from the repository root.</p>`});
function bind(){const search=$("search");search.addEventListener("input",()=>suggest(search.value));document.querySelectorAll("[data-direction]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-direction]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.direction=b.dataset.direction;render()}));$("limit").addEventListener("input",e=>{state.limit=Number(e.target.value);$("limit-value").textContent=state.limit;render()});$("reset").addEventListener("click",()=>select(canonical));suggest("")}
function suggest(q){q=q.trim().toLowerCase();const ranked=state.graph.nodes.filter(n=>!q||n.id.toLowerCase().includes(q)).slice(0,10);$("suggestions").innerHTML=ranked.map(n=>`<button data-id="${esc(n.id)}">${esc(short(n.id))}</button>`).join("");$("suggestions").querySelectorAll("button").forEach(b=>b.onclick=()=>{select(b.dataset.id);$("search").value="";suggest("")})}
function select(id){state.selected=id;state.edge=null;render()}
function neighborhood(){const incoming=state.graph.edges.filter(e=>e.to===state.selected).slice(0,state.limit);const outgoing=state.graph.edges.filter(e=>e.from===state.selected).slice(0,state.limit);return {incoming:state.direction==="outgoing"?[]:incoming,outgoing:state.direction==="incoming"?[]:outgoing}}
function render(){if(!state.graph)return;$("selected-title").textContent=short(state.selected);const {incoming,outgoing}=neighborhood();const visible=incoming.length+outgoing.length;$("visible-status").textContent=`Showing ${visible} connection${visible===1?"":"s"} · ${incoming.length} upstream · ${outgoing.length} downstream`;$("empty").hidden=visible>0;const svg=$("graph"),w=svg.clientWidth||720,h=svg.clientHeight||600,cx=w/2,cy=h/2;$("lane-labels").innerHTML=`<line class="lane-rule" x1="28" y1="56" x2="${w-28}" y2="56"></line><text class="lane-label" x="28" y="43">Provides required data</text><text class="lane-label" x="${cx}" y="43" text-anchor="middle">Selected operation</text><text class="lane-label" x="${w-28}" y="43" text-anchor="end">Consumes output data</text>`;const layout=[];const place=(edges,x,kind,getId)=>edges.forEach((e,i)=>layout.push({id:getId(e),x,y:76+(i+1)*(h-96)/(edges.length+1),kind}));place(incoming,110,"producer-node",e=>e.from);place(outgoing,w-110,"consumer-node",e=>e.to);layout.push({id:state.selected,x:cx,y:Math.max(100,cy+22),kind:"focus-node"});const pos=new Map(layout.map(n=>[n.id,n]));const all=[...incoming,...outgoing];$("edges").innerHTML=all.map(e=>{const a=pos.get(e.from),b=pos.get(e.to);if(!a||!b)return"";const mid=(a.x+b.x)/2,key=`${e.from}\0${e.to}\0${e.label}`;return `<g><path class="edge ${state.edge===key?"selected":""}" data-key="${esc(key)}" d="M${a.x},${a.y} C${mid},${a.y} ${mid},${b.y} ${b.x},${b.y}"></path><text class="edge-label" x="${mid}" y="${(a.y+b.y)/2-5}" text-anchor="middle">${esc(e.label)}</text></g>`}).join("");$("nodes").innerHTML=layout.map(n=>`<g class="node ${n.kind}" data-id="${esc(n.id)}" transform="translate(${n.x-82},${n.y-20})"><rect width="164" height="40"></rect><text x="82" y="24" text-anchor="middle">${esc(short(n.id).slice(0,25))}</text></g>`).join("");$("nodes").querySelectorAll(".node").forEach(n=>n.onclick=()=>select(n.dataset.id));$("edges").querySelectorAll(".edge").forEach(p=>p.onclick=()=>{state.edge=p.dataset.key;render();inspect(all.find(e=>`${e.from}\0${e.to}\0${e.label}`===state.edge))});if(!state.edge)inspectNode(incoming,outgoing)}
function findEvidence(edge){const c=state.report.cases.find(x=>x.consumer===edge.to&&x.required_input.name===edge.label);const candidate=c?.candidates.find(x=>x.producer===edge.from);return {case:c,candidate}}
function inspectNode(incoming,outgoing){$("inspector-content").innerHTML=`<h3>${esc(short(state.selected))}</h3><p class="muted">${incoming.length} visible input${incoming.length===1?"":"s"} · ${outgoing.length} visible output${outgoing.length===1?"":"s"}</p><div class="field"><span>Catalog slug</span><code>${esc(state.selected)}</code></div><p class="muted">Choose a labeled connection to inspect its schema evidence and adjudication.</p>`}
function inspect(edge){if(!edge)return;const {case:c,candidate:x}=findEvidence(edge);$("inspector-content").innerHTML=`<span class="badge">${esc(x?.confidence||"catalog")}</span><h3>${esc(edge.label)}</h3><div class="flow"><span>${esc(short(edge.from))}</span><i>→</i><span>${esc(short(edge.to))}</span></div><div class="field"><span>Required input</span><code>${esc(c?.required_input.path||edge.label)}</code></div><div class="field"><span>Producer output</span><code>${esc(x?.output_path||"catalog output")}</code></div><div class="field"><span>Evidence score</span><code>${esc(x?.score??"—")} · rank ${esc(x?.rank??"—")}</code></div>${c?.rationale?`<div class="field"><span>Model rationale</span><p>${esc(c.rationale)}</p></div>`:""}<div class="field"><span>Weighted evidence</span><ul class="evidence">${(x?.evidence||[]).map(e=>`<li>${esc(e.detail)} <b>${e.weight>0?"+":""}${e.weight}</b></li>`).join("")||"<li>No detailed evidence in report.</li>"}</ul></div>`}
window.addEventListener("resize",()=>render());
