const $=id=>document.getElementById(id);
const initialView=new URLSearchParams(location.search).get("view")==="focus"?"focus":"atlas";
const state={graph:null,report:null,view:initialView,selected:"GITHUB_CREATE_AN_ISSUE_COMMENT",direction:"both",limit:24,rotationX:-.18,rotationY:.35,zoom:1,drag:false,last:null,down:null,hover:null,hoverEdge:null,activeEdge:null,screen:[],edgeScreen:[]};
const ctx=$("scene").getContext("2d");
const short=s=>s.replace(/^GITHUB_/,"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const edgeKey=e=>`${e.from}\0${e.to}\0${e.label}`;
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};

Promise.all([fetch("/dependency_graph.json").then(ok),fetch("/inference_report.json").then(ok)]).then(([graph,report])=>{
  state.graph=graph;state.report=report;
  if(!graph.nodes.some(n=>n.id===state.selected))state.selected=graph.nodes[0]?.id;
  buildModel();bind();select(state.selected);$("node-count").textContent=graph.nodes.length.toLocaleString();$("edge-count").textContent=graph.edges.length.toLocaleString();$("mode").textContent=report.run?.mode||"catalog";$("loading").classList.add("done");requestAnimationFrame(draw);
}).catch(e=>{$("loading").innerHTML=`Unable to load graph · ${esc(e.message)}`});
function ok(r){if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}
function buildModel(){
  const degree=new Map(state.graph.nodes.map(n=>[n.id,0]));
  state.graph.edges.forEach(e=>{degree.set(e.from,(degree.get(e.from)||0)+1);degree.set(e.to,(degree.get(e.to)||0)+1)});
  const n=state.graph.nodes.length,phi=Math.PI*(3-Math.sqrt(5));
  state.points=new Map(state.graph.nodes.map((node,i)=>{const y=1-(i/(n-1))*2,r=Math.sqrt(1-y*y),theta=phi*i+(hash(node.id)%100)/1000,hub=Math.min(1,(degree.get(node.id)||0)/35),radius=290-70*hub;return[node.id,{id:node.id,x:Math.cos(theta)*r*radius,y:y*radius,z:Math.sin(theta)*r*radius,degree:degree.get(node.id)||0}]}));
  state.adj=new Map(state.graph.nodes.map(n=>[n.id,[]]));state.graph.edges.forEach(e=>{state.adj.get(e.from)?.push(e);state.adj.get(e.to)?.push(e)});
}
function bind(){
  document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===state.view));$("view-label").textContent=state.view==="atlas"?"Selected operation":"Focused dependency flow";
  document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.view=b.dataset.view;$("view-label").textContent=state.view==="atlas"?"Selected operation":"Focused dependency flow";draw()});
  document.querySelectorAll("[data-direction]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-direction]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.direction=b.dataset.direction;renderSide();draw()});
  $("limit").oninput=e=>{state.limit=+e.target.value;$("limit-value").textContent=state.limit;renderSide();draw()};
  $("search").oninput=e=>results(e.target.value);$("search").onkeydown=e=>{if(e.key==="Enter")$("results").querySelector("button")?.click()};
  document.addEventListener("keydown",e=>{if(e.key==="/"&&!/input/i.test(document.activeElement.tagName)){e.preventDefault();$("search").focus()}});
  $("reset").onclick=()=>{state.rotationX=-.18;state.rotationY=.35;state.zoom=1;state.view="atlas";document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view==="atlas"));select("GITHUB_CREATE_AN_ISSUE_COMMENT")};
  const c=$("scene");c.onpointerdown=e=>{state.drag=true;state.down=[e.clientX,e.clientY];state.last=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId);c.classList.add("dragging")};
  c.onpointermove=e=>{if(state.drag&&state.view==="atlas"){state.rotationY+=(e.clientX-state.last[0])*.006;state.rotationX+=(e.clientY-state.last[1])*.006;state.last=[e.clientX,e.clientY];draw();return}const hit=hitTest(e.clientX,e.clientY);state.hover=hit.node;state.hoverEdge=hit.edge;c.style.cursor=hit.node||hit.edge?"pointer":state.view==="atlas"?"grab":"default";draw()};
  c.onpointerup=e=>{const moved=state.down&&Math.hypot(e.clientX-state.down[0],e.clientY-state.down[1]);state.drag=false;c.classList.remove("dragging");if((moved||0)<5){if(state.hover)select(state.hover);else if(state.hoverEdge)activateEdge(state.hoverEdge)}};
  c.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(2.2,state.zoom*Math.exp(-e.deltaY*.001)));draw()};window.onresize=resize;resize();results("");
}
function results(q){q=q.trim().toLowerCase();const nodes=state.graph.nodes.filter(n=>!q||n.id.toLowerCase().includes(q)).sort((a,b)=>(state.points.get(b.id).degree-state.points.get(a.id).degree)).slice(0,8);$("results").innerHTML=nodes.map(n=>`<button data-id="${esc(n.id)}">${esc(n.id)}</button>`).join("");$("results").querySelectorAll("button").forEach(b=>b.onclick=()=>{select(b.dataset.id);$("search").value="";results("")})}
function select(id){state.selected=id;state.activeEdge=null;$("selected-title").textContent=short(id);const edges=visibleEdges();const ins=edges.filter(e=>e.to===id).length,outs=edges.filter(e=>e.from===id).length;$("selected-meta").textContent=`${ins} upstream · ${outs} downstream · click any connected node to continue`;renderSide();draw()}
function visibleEdges(){const all=state.adj.get(state.selected)||[],incoming=all.filter(e=>e.to===state.selected).slice(0,state.limit),outgoing=all.filter(e=>e.from===state.selected).slice(0,state.limit);return state.direction==="incoming"?incoming:state.direction==="outgoing"?outgoing:[...incoming,...outgoing]}
function renderSide(){if(!state.graph)return;const edges=visibleEdges();$("connection-count").textContent=edges.length;$("connections").innerHTML=edges.map(e=>{const incoming=e.to===state.selected,other=incoming?e.from:e.to;return`<button class="connection ${incoming?"in":"out"} ${state.activeEdge===edgeKey(e)?"active":""}" data-key="${esc(edgeKey(e))}"><i></i><span><b>${esc(short(other))}</b><small>${incoming?"provides":"receives"} ${esc(e.label)}</small></span><em>${incoming?"IN":"OUT"}</em></button>`}).join("")||`<p style="padding:12px;color:#727e90">No dependencies in this direction.</p>`;$("connections").querySelectorAll("button").forEach(b=>b.onclick=()=>{const e=edges.find(x=>edgeKey(x)===b.dataset.key);state.activeEdge=b.dataset.key;renderSide();inspect(e);draw()});if(!state.activeEdge)$("evidence").innerHTML=`<p>Select a connection to inspect its schema path and weighted evidence.</p>`}
function inspect(edge){const c=state.report.cases?.find(x=>x.consumer===edge.to&&x.required_input.name===edge.label),x=c?.candidates?.find(x=>x.producer===edge.from);$("evidence").innerHTML=`<span class="overline">${esc(x?.confidence||"catalog")} confidence · score ${esc(x?.score??"—")}</span><h3>${esc(edge.label)}</h3><p>${esc(short(edge.from))} → ${esc(short(edge.to))}</p><span class="overline">Output path</span><code>${esc(x?.output_path||"catalog output")}</code><span class="overline">Required input</span><code>${esc(c?.required_input?.path||edge.label)}</code><ul class="evidence-list">${(x?.evidence||[]).map(v=>`<li><span>${esc(v.detail)}</span><b>${v.weight>0?"+":""}${v.weight}</b></li>`).join("")||"<li>No detailed evidence recorded.</li>"}</ul>`}
function activateEdge(edge){state.activeEdge=edgeKey(edge);renderSide();inspect(edge);draw()}
function resize(){const d=devicePixelRatio||1,c=$("scene");c.width=innerWidth*d;c.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function project(p){let{x,y,z}=p;const cy=Math.cos(state.rotationY),sy=Math.sin(state.rotationY),cx=Math.cos(state.rotationX),sx=Math.sin(state.rotationX),x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y*cx-z1*sx,z2=y*sx+z1*cx,depth=720+z2,scale=state.zoom*680/depth;return{x:innerWidth/2+(x1*scale),y:innerHeight/2+34+(y1*scale),z:z2,scale}}
function focusEdges(){const all=visibleEdges(),incoming=all.filter(e=>e.to===state.selected).slice(0,10),outgoing=all.filter(e=>e.from===state.selected).slice(0,10);return[...incoming,...outgoing]}
function focusLayout(edges){const incoming=edges.filter(e=>e.to===state.selected),outgoing=edges.filter(e=>e.from===state.selected),left=innerWidth>1100?430:310,right=innerWidth>1100?innerWidth-455:innerWidth-310,center=(left+right)/2,map=new Map([[state.selected,{x:center,y:innerHeight/2+35,z:100,scale:1.25,card:true}]]);const place=(arr,x,get)=>arr.forEach((e,i)=>map.set(get(e),{x,y:235+(i+.5)*(innerHeight-300)/Math.max(1,arr.length),z:0,scale:1,card:true}));place(incoming,left,e=>e.from);place(outgoing,right,e=>e.to);return map}
function segmentDistance(px,py,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/l));return Math.hypot(px-(a.x+t*dx),py-(a.y+t*dy))}
function hitTest(x,y){for(const p of [...state.screen].reverse()){if(p.card?Math.abs(x-p.x)<106&&Math.abs(y-p.y)<24:Math.hypot(x-p.x,y-p.y)<15)return{node:p.id,edge:null}}let best=null,dist=9;for(const item of state.edgeScreen){const d=segmentDistance(x,y,item.a,item.b);if(d<dist){dist=d;best=item.edge}}return{node:null,edge:best}}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function arrow(x,y,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y-4);ctx.lineTo(x-7,y+4);ctx.closePath();ctx.fill()}
function draw(){if(!state.graph)return;ctx.clearRect(0,0,innerWidth,innerHeight);const allVisible=visibleEdges(),connected=new Set([state.selected]);allVisible.forEach(e=>{connected.add(e.from);connected.add(e.to)});const displayEdges=state.view==="focus"?focusEdges():state.graph.edges,pos=state.view==="focus"?focusLayout(displayEdges):new Map([...state.points].map(([id,p])=>[id,project(p)]));state.edgeScreen=[];
  if(state.view==="focus"){const left=innerWidth>1100?430:310,right=innerWidth>1100?innerWidth-455:innerWidth-310,center=(left+right)/2;ctx.font="700 9px Segoe UI, sans-serif";ctx.fillStyle="#697487";ctx.textAlign="center";ctx.fillText("UPSTREAM PROVIDERS",left,245);ctx.fillText("SELECTED OPERATION",center,245);ctx.fillText("DOWNSTREAM CONSUMERS",right,245)}
  for(const e of displayEdges){const a=pos.get(e.from),b=pos.get(e.to);if(!a||!b)continue;const active=edgeKey(e)===state.activeEdge,hover=edgeKey(e)===edgeKey(state.hoverEdge||{}),near=connected.has(e.from)&&connected.has(e.to),color=active||hover?"rgba(255,198,109,.95)":near?"rgba(103,232,210,.38)":"rgba(122,162,255,.045)";ctx.strokeStyle=color;ctx.lineWidth=active||hover?2.4:near?1.2:.55;const start={x:a.x+(state.view==="focus"?104:0),y:a.y},end={x:b.x-(state.view==="focus"?104:0),y:b.y};ctx.beginPath();ctx.moveTo(start.x,start.y);if(state.view==="focus"){const mid=(start.x+end.x)/2;ctx.bezierCurveTo(mid,start.y,mid,end.y,end.x,end.y)}else ctx.lineTo(end.x,end.y);ctx.stroke();if(state.view==="focus"||near)state.edgeScreen.push({edge:e,a:start,b:end});if(state.view==="focus"){arrow(end.x,end.y,color);const mx=(start.x+end.x)/2,my=(start.y+end.y)/2,label=e.label,w=Math.min(150,ctx.measureText(label).width+16);roundedRect(mx-w/2,my-10,w,20,7);ctx.fillStyle="#0c1119";ctx.fill();ctx.strokeStyle=active||hover?"#ffc66d88":"#ffffff18";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=active||hover?"#ffd28b":"#a6b1c1";ctx.font="9px Consolas, monospace";ctx.textAlign="center";ctx.fillText(label.slice(0,24),mx,my+3)}else if(active||hover){const mx=(start.x+end.x)/2,my=(start.y+end.y)/2,label=`${e.label} · click for evidence`,w=Math.min(190,ctx.measureText(label).width+18);roundedRect(mx-w/2,my-11,w,22,7);ctx.fillStyle="#111720";ctx.fill();ctx.strokeStyle="#ffc66d88";ctx.stroke();ctx.fillStyle="#ffd28b";ctx.font="9px Segoe UI, sans-serif";ctx.textAlign="center";ctx.fillText(label,mx,my+3)}}
  const visible=state.view==="focus"?[...pos.keys()]:[...state.points.keys()];const ordered=visible.map(id=>({id,...pos.get(id),degree:state.points.get(id)?.degree||0})).filter(p=>p.x>300&&p.x<innerWidth-345&&p.y>70&&p.y<innerHeight+20).sort((a,b)=>a.z-b.z);state.screen=ordered;
  for(const p of ordered){const selected=p.id===state.selected,hover=p.id===state.hover,near=connected.has(p.id);if(state.view==="focus"){roundedRect(p.x-104,p.y-23,208,46,10);ctx.fillStyle=selected?"#122a2a":hover?"#1b2432":"#101620";ctx.fill();ctx.strokeStyle=selected?"#67e8d2":hover?"#d8e1ee":near?"#6685bd":"#354153";ctx.lineWidth=selected?1.7:1;ctx.stroke();ctx.beginPath();ctx.arc(p.x-86,p.y,4,0,Math.PI*2);ctx.fillStyle=selected?"#67e8d2":p.id===state.selected?"#67e8d2":"#7aa2ff";ctx.fill();ctx.fillStyle=selected?"#f4f7fb":"#c4cddd";ctx.font=selected?"600 10px Segoe UI, sans-serif":"10px Segoe UI, sans-serif";ctx.textAlign="left";ctx.fillText(short(p.id).slice(0,30),p.x-74,p.y+3);continue}const r=Math.max(2,Math.min(10,(2+Math.sqrt(p.degree)*.6)*p.scale));if(selected||hover){ctx.beginPath();ctx.arc(p.x,p.y,r+9,0,Math.PI*2);ctx.fillStyle=selected?"rgba(103,232,210,.16)":"rgba(255,255,255,.1)";ctx.fill()}ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=selected?"#67e8d2":near?"#8eabff":`rgba(125,151,196,${Math.max(.1,.38+p.z/1300)})`;ctx.fill();if(selected||hover||near){ctx.font=selected?"600 11px Segoe UI, sans-serif":"10px Segoe UI, sans-serif";ctx.fillStyle=selected?"#f4f7fb":"#b9c3d1";ctx.textAlign="center";ctx.fillText(short(p.id).slice(0,38),p.x,p.y-r-9)}}
  if(state.view==="focus"&&allVisible.length>displayEdges.length){ctx.fillStyle="#778295";ctx.font="10px Segoe UI, sans-serif";ctx.textAlign="center";ctx.fillText(`${allVisible.length-displayEdges.length} more connections remain available in the inspector`,pos.get(state.selected).x,innerHeight-34)}
}
